// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Identifier struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SMSStatus struct {
	Id                   *Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sms                  *SMS        `protobuf:"bytes,2,opt,name=sms,proto3" json:"sms,omitempty"`
	Status               string      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Uri                  string      `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SMSStatus) Reset()         { *m = SMSStatus{} }
func (m *SMSStatus) String() string { return proto.CompactTextString(m) }
func (*SMSStatus) ProtoMessage()    {}
func (*SMSStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *SMSStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSStatus.Unmarshal(m, b)
}
func (m *SMSStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSStatus.Marshal(b, m, deterministic)
}
func (m *SMSStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSStatus.Merge(m, src)
}
func (m *SMSStatus) XXX_Size() int {
	return xxx_messageInfo_SMSStatus.Size(m)
}
func (m *SMSStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SMSStatus proto.InternalMessageInfo

func (m *SMSStatus) GetId() *Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *SMSStatus) GetSms() *SMS {
	if m != nil {
		return m.Sms
	}
	return nil
}

func (m *SMSStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SMSStatus) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type SMS struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MediaURL             string   `protobuf:"bytes,3,opt,name=mediaURL,proto3" json:"mediaURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMS) Reset()         { *m = SMS{} }
func (m *SMS) String() string { return proto.CompactTextString(m) }
func (*SMS) ProtoMessage()    {}
func (*SMS) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *SMS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMS.Unmarshal(m, b)
}
func (m *SMS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMS.Marshal(b, m, deterministic)
}
func (m *SMS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMS.Merge(m, src)
}
func (m *SMS) XXX_Size() int {
	return xxx_messageInfo_SMS.Size(m)
}
func (m *SMS) XXX_DiscardUnknown() {
	xxx_messageInfo_SMS.DiscardUnknown(m)
}

var xxx_messageInfo_SMS proto.InternalMessageInfo

func (m *SMS) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SMS) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SMS) GetMediaURL() string {
	if m != nil {
		return m.MediaURL
	}
	return ""
}

type Email struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              *Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Email) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Call struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Callback             string   `protobuf:"bytes,2,opt,name=callback,proto3" json:"callback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Call) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

type Message struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UserInfo struct {
	Name                 string        `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	GivenName            string        `protobuf:"bytes,7,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName           string        `protobuf:"bytes,8,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Gender               string        `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthdate            string        `protobuf:"bytes,10,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Email                string        `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	Picture              string        `protobuf:"bytes,12,opt,name=picture,proto3" json:"picture,omitempty"`
	UserMetadata         *UserMetadata `protobuf:"bytes,13,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	AppMetadata          *AppMetadata  `protobuf:"bytes,14,opt,name=app_metadata,json=appMetadata,proto3" json:"app_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *UserInfo) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *UserInfo) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserInfo) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *UserInfo) GetUserMetadata() *UserMetadata {
	if m != nil {
		return m.UserMetadata
	}
	return nil
}

func (m *UserInfo) GetAppMetadata() *AppMetadata {
	if m != nil {
		return m.AppMetadata
	}
	return nil
}

type UserMetadata struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	PreferredContact     string   `protobuf:"bytes,2,opt,name=preferred_contact,json=preferredContact,proto3" json:"preferred_contact,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMetadata) Reset()         { *m = UserMetadata{} }
func (m *UserMetadata) String() string { return proto.CompactTextString(m) }
func (*UserMetadata) ProtoMessage()    {}
func (*UserMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *UserMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMetadata.Unmarshal(m, b)
}
func (m *UserMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMetadata.Marshal(b, m, deterministic)
}
func (m *UserMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMetadata.Merge(m, src)
}
func (m *UserMetadata) XXX_Size() int {
	return xxx_messageInfo_UserMetadata.Size(m)
}
func (m *UserMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_UserMetadata proto.InternalMessageInfo

func (m *UserMetadata) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserMetadata) GetPreferredContact() string {
	if m != nil {
		return m.PreferredContact
	}
	return ""
}

func (m *UserMetadata) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserMetadata) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AppMetadata struct {
	Plan                 string   `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	PayToken             string   `protobuf:"bytes,2,opt,name=pay_token,json=payToken,proto3" json:"pay_token,omitempty"`
	Delinquent           string   `protobuf:"bytes,3,opt,name=delinquent,proto3" json:"delinquent,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppMetadata) Reset()         { *m = AppMetadata{} }
func (m *AppMetadata) String() string { return proto.CompactTextString(m) }
func (*AppMetadata) ProtoMessage()    {}
func (*AppMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *AppMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMetadata.Unmarshal(m, b)
}
func (m *AppMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMetadata.Marshal(b, m, deterministic)
}
func (m *AppMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMetadata.Merge(m, src)
}
func (m *AppMetadata) XXX_Size() int {
	return xxx_messageInfo_AppMetadata.Size(m)
}
func (m *AppMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_AppMetadata proto.InternalMessageInfo

func (m *AppMetadata) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *AppMetadata) GetPayToken() string {
	if m != nil {
		return m.PayToken
	}
	return ""
}

func (m *AppMetadata) GetDelinquent() string {
	if m != nil {
		return m.Delinquent
	}
	return ""
}

func (m *AppMetadata) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Auth struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string   `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Redirect             string   `protobuf:"bytes,4,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Audience             string   `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	Scopes               []string `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Auth) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Auth) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *Auth) GetRedirect() string {
	if m != nil {
		return m.Redirect
	}
	return ""
}

func (m *Auth) GetAudience() string {
	if m != nil {
		return m.Audience
	}
	return ""
}

func (m *Auth) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type Bytes struct {
	Bits                 []byte   `protobuf:"bytes,1,opt,name=bits,proto3" json:"bits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetBits() []byte {
	if m != nil {
		return m.Bits
	}
	return nil
}

type Template struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Template) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Identifier)(nil), "api.Identifier")
	proto.RegisterType((*SMSStatus)(nil), "api.SMSStatus")
	proto.RegisterType((*SMS)(nil), "api.SMS")
	proto.RegisterType((*Email)(nil), "api.Email")
	proto.RegisterType((*Call)(nil), "api.Call")
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterType((*UserInfo)(nil), "api.UserInfo")
	proto.RegisterType((*UserMetadata)(nil), "api.UserMetadata")
	proto.RegisterType((*AppMetadata)(nil), "api.AppMetadata")
	proto.RegisterType((*Auth)(nil), "api.Auth")
	proto.RegisterType((*Bytes)(nil), "api.Bytes")
	proto.RegisterType((*Template)(nil), "api.Template")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 996 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x96, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xc7, 0x11, 0xdb, 0x71, 0xac, 0x63, 0x27, 0x4b, 0xb8, 0x2e, 0xd3, 0xdc, 0xa4, 0x09, 0x54,
	0x60, 0x18, 0x36, 0xa0, 0x02, 0x52, 0x60, 0x17, 0xc3, 0x6e, 0xd2, 0x2c, 0xe8, 0xb2, 0xd5, 0x1d,
	0x60, 0x35, 0xc0, 0x7a, 0x15, 0xd0, 0xd2, 0x89, 0xcd, 0x56, 0xa2, 0x34, 0x92, 0x0a, 0x6a, 0x14,
	0xb9, 0xd9, 0x2b, 0xec, 0x45, 0x36, 0xec, 0x51, 0xf6, 0x0a, 0xbb, 0xd8, 0x63, 0x0c, 0x3c, 0x94,
	0x14, 0xbb, 0x69, 0x0d, 0x34, 0x77, 0xe7, 0x83, 0xff, 0xdf, 0x39, 0x3c, 0xa2, 0x44, 0x81, 0xc7,
	0x0b, 0xf1, 0xa8, 0x50, 0xb9, 0xc9, 0x59, 0x9b, 0x17, 0x62, 0xb8, 0x37, 0xcd, 0xf3, 0x69, 0x8a,
	0x21, 0x2f, 0x44, 0xc8, 0xa5, 0xcc, 0x0d, 0x37, 0x22, 0x97, 0xda, 0x2d, 0x09, 0xf6, 0x00, 0xce,
	0x12, 0x94, 0x46, 0x5c, 0x0a, 0x54, 0x6c, 0x0b, 0x5a, 0x22, 0xf1, 0xd7, 0x0e, 0xd7, 0xbe, 0xf2,
	0xc6, 0x2d, 0x91, 0x04, 0x0a, 0xbc, 0x68, 0x14, 0x45, 0x86, 0x9b, 0x52, 0xb3, 0x83, 0x26, 0xd9,
	0x3f, 0xfa, 0xe4, 0x91, 0xad, 0x72, 0xa3, 0xb4, 0xab, 0xd9, 0x10, 0xda, 0x3a, 0xd3, 0x7e, 0x8b,
	0x56, 0xf4, 0x68, 0x45, 0x34, 0x8a, 0xc6, 0x36, 0xc8, 0x76, 0xa1, 0xab, 0x09, 0xe3, 0xb7, 0x89,
	0x5e, 0x79, 0x6c, 0x1b, 0xda, 0xa5, 0x12, 0x7e, 0x87, 0x82, 0xd6, 0x0c, 0x5e, 0x42, 0x3b, 0x1a,
	0x45, 0xb6, 0x15, 0x93, 0xd7, 0xad, 0x98, 0x9c, 0x7d, 0x09, 0x1b, 0x19, 0x6a, 0xcd, 0xa7, 0x58,
	0x15, 0x18, 0x50, 0x81, 0x91, 0x8b, 0x8d, 0xeb, 0x24, 0x1b, 0x42, 0x2f, 0xc3, 0x44, 0xf0, 0xf3,
	0xf1, 0xb3, 0xaa, 0x54, 0xe3, 0x07, 0x31, 0xac, 0x9f, 0x66, 0x5c, 0xa4, 0xcc, 0x87, 0x0d, 0x9e,
	0x24, 0x0a, 0xb5, 0xae, 0x2a, 0xd4, 0xae, 0xcd, 0xe8, 0x72, 0xf2, 0x0a, 0x63, 0x43, 0x65, 0xbc,
	0x71, 0xed, 0x2e, 0x36, 0xd0, 0x5e, 0xd1, 0x40, 0x70, 0x04, 0x9d, 0x13, 0x9e, 0xa6, 0xb7, 0x36,
	0x30, 0x84, 0x5e, 0xcc, 0xd3, 0x74, 0xc2, 0xe3, 0xd7, 0x15, 0xba, 0xf1, 0x83, 0x03, 0xd8, 0xa8,
	0x38, 0xec, 0x1e, 0xac, 0x5f, 0xf1, 0xb4, 0xc4, 0x4a, 0xe9, 0x9c, 0xe0, 0xaf, 0x16, 0xf4, 0xce,
	0x35, 0xaa, 0x33, 0x79, 0x99, 0x33, 0x06, 0x1d, 0xc9, 0x33, 0xf4, 0xbb, 0xb4, 0x82, 0x6c, 0xb6,
	0x0f, 0x30, 0x15, 0x57, 0x28, 0x2f, 0x28, 0xb3, 0x41, 0x19, 0x8f, 0x22, 0xcf, 0x6d, 0xfa, 0x00,
	0xfa, 0x97, 0x3c, 0x13, 0xe9, 0xdc, 0xe5, 0x7b, 0x94, 0x07, 0x17, 0xa2, 0x05, 0xbb, 0xd0, 0x9d,
	0xa2, 0x4c, 0x50, 0xf9, 0x9e, 0x7b, 0x3e, 0xce, 0x63, 0x7b, 0xe0, 0x4d, 0x84, 0x32, 0xb3, 0x84,
	0x1b, 0xf4, 0xc1, 0x61, 0x9b, 0x80, 0x6d, 0x16, 0xed, 0x40, 0xfd, 0xbe, 0x6b, 0x16, 0xeb, 0xe9,
	0x16, 0x22, 0x36, 0xa5, 0x42, 0x7f, 0xe0, 0x66, 0x58, 0xb9, 0xec, 0x5b, 0xd8, 0x2c, 0x35, 0xaa,
	0x8b, 0x0c, 0x0d, 0x4f, 0xb8, 0xe1, 0xfe, 0x26, 0x4d, 0x72, 0x87, 0x26, 0x69, 0xf7, 0x37, 0xaa,
	0x12, 0xe3, 0x41, 0xb9, 0xe0, 0xb1, 0xc7, 0x30, 0xe0, 0x45, 0x71, 0x23, 0xdb, 0x22, 0xd9, 0x36,
	0xc9, 0x8e, 0x8b, 0xa2, 0x51, 0xf5, 0xf9, 0x8d, 0x13, 0x5c, 0xc3, 0x60, 0x11, 0x69, 0x9b, 0x2d,
	0x66, 0xb9, 0x6c, 0x26, 0x4b, 0x0e, 0xfb, 0x06, 0x76, 0x0a, 0x85, 0x97, 0xa8, 0x14, 0x26, 0x17,
	0x71, 0x2e, 0x0d, 0x6f, 0x1e, 0xfd, 0x76, 0x93, 0x38, 0x71, 0xf1, 0x0f, 0x9e, 0x62, 0x06, 0x1d,
	0xc3, 0xa7, 0xda, 0xef, 0x1c, 0xb6, 0xed, 0x13, 0xb1, 0x76, 0xa0, 0xa0, 0xbf, 0xd0, 0x9a, 0x5d,
	0x52, 0xa4, 0x5c, 0x56, 0xc5, 0xc9, 0x66, 0xf7, 0xc1, 0x2b, 0xf8, 0xfc, 0xc2, 0xe4, 0xaf, 0x51,
	0xd6, 0x67, 0xa2, 0xe0, 0xf3, 0x17, 0xd6, 0x67, 0x0f, 0x00, 0x12, 0x4c, 0x85, 0xfc, 0xad, 0x44,
	0x69, 0xaa, 0x7a, 0x0b, 0x91, 0xf7, 0xd6, 0xfc, 0x73, 0x0d, 0x3a, 0xc7, 0xa5, 0x99, 0xd9, 0x46,
	0x93, 0x3c, 0xe3, 0xa2, 0xae, 0x57, 0x79, 0xb6, 0x62, 0x9c, 0x0a, 0x94, 0xe6, 0x42, 0x24, 0xcd,
	0x29, 0xa4, 0xc0, 0x59, 0xc2, 0x1e, 0xc2, 0x66, 0x95, 0xd4, 0x18, 0x2b, 0xac, 0x8b, 0x0e, 0x5c,
	0x30, 0xa2, 0x98, 0x3d, 0xc6, 0x0a, 0x13, 0xa1, 0xec, 0x1b, 0xe2, 0xde, 0xda, 0xc6, 0xb7, 0x39,
	0x5e, 0x26, 0x02, 0x65, 0x8c, 0xfe, 0xba, 0xcb, 0xd5, 0x3e, 0x8d, 0x2e, 0xce, 0x0b, 0xd4, 0x7e,
	0x97, 0x1a, 0xae, 0xbc, 0xe0, 0x3e, 0xac, 0x3f, 0x99, 0x1b, 0xa4, 0x19, 0x4e, 0x84, 0x71, 0x2f,
	0xe4, 0x60, 0x4c, 0x76, 0x70, 0x04, 0xbd, 0x17, 0x98, 0x15, 0xa9, 0x3d, 0x6b, 0x76, 0xbf, 0xf8,
	0xc6, 0xd4, 0x03, 0xb4, 0xb6, 0x8d, 0xd1, 0x79, 0x68, 0x39, 0x8d, 0xb5, 0x8f, 0xfe, 0x5b, 0x87,
	0xad, 0x73, 0x23, 0x52, 0x61, 0xe6, 0x11, 0xaa, 0x2b, 0x11, 0x23, 0xfb, 0x1e, 0x3a, 0xa7, 0xf1,
	0x2c, 0x67, 0x4b, 0x6f, 0xec, 0x70, 0xc9, 0x0b, 0xfc, 0xdf, 0xff, 0xf9, 0xf7, 0x8f, 0x16, 0x0b,
	0x36, 0xc3, 0xd2, 0x89, 0x43, 0x8c, 0x67, 0xf9, 0x77, 0x6b, 0x5f, 0xb3, 0x9f, 0xa1, 0x6f, 0xd5,
	0x51, 0xc1, 0xa5, 0xd0, 0xb3, 0x95, 0x90, 0x43, 0x82, 0x0c, 0x83, 0xcf, 0x96, 0x20, 0xa1, 0x76,
	0xd2, 0x05, 0xd8, 0xc9, 0x4c, 0x48, 0xd4, 0x78, 0x17, 0x58, 0xec, 0xa4, 0x0b, 0xb0, 0x53, 0x39,
	0x4d, 0xef, 0xd8, 0x19, 0x3a, 0xa9, 0x85, 0x3d, 0x05, 0xcf, 0xc2, 0x7e, 0x14, 0x32, 0x11, 0x2b,
	0x51, 0x0f, 0x08, 0xe5, 0x07, 0x9f, 0x2e, 0xa3, 0x66, 0x56, 0x68, 0x41, 0x67, 0x00, 0x16, 0x74,
	0xac, 0xf8, 0x44, 0xc4, 0x2b, 0x49, 0x07, 0x44, 0xfa, 0x22, 0xb8, 0xb7, 0x4c, 0xe2, 0xa4, 0x74,
	0x3d, 0xf5, 0x47, 0x5c, 0xe9, 0x19, 0x4f, 0x7f, 0x8a, 0x7e, 0x79, 0xce, 0x80, 0xd4, 0x74, 0x5c,
	0x86, 0x0b, 0xf6, 0x7b, 0x36, 0x97, 0x39, 0x55, 0xf8, 0x4a, 0xe7, 0x72, 0x19, 0xf4, 0xf2, 0x78,
	0xf4, 0xec, 0x0e, 0xa0, 0x39, 0xcf, 0x52, 0x0b, 0x3a, 0x05, 0xa8, 0x40, 0xbf, 0xae, 0xe0, 0xdc,
	0xde, 0x58, 0xcd, 0x79, 0xe3, 0x30, 0x3f, 0x40, 0x77, 0xec, 0x3e, 0xb0, 0x9b, 0x24, 0xab, 0x4f,
	0xf9, 0x47, 0x51, 0x8e, 0xfe, 0x6e, 0xc1, 0x56, 0xf5, 0x69, 0xaa, 0x8f, 0xfa, 0x13, 0xd8, 0x88,
	0x50, 0x26, 0xf6, 0x06, 0x6d, 0x6e, 0xe0, 0xe1, 0xbb, 0xb7, 0x75, 0xb0, 0x47, 0xe4, 0xdd, 0x60,
	0x27, 0xac, 0xbe, 0x78, 0xa1, 0xce, 0x74, 0xf8, 0xd6, 0xe4, 0xd7, 0x6e, 0x58, 0xdd, 0xa7, 0x68,
	0x2c, 0xe2, 0x5d, 0xe1, 0x70, 0xab, 0x66, 0xba, 0x7f, 0x82, 0x0f, 0x81, 0x44, 0x42, 0xa0, 0x11,
	0x78, 0xb6, 0x19, 0x77, 0xe7, 0xba, 0x9d, 0x91, 0x7d, 0xbb, 0xa1, 0x87, 0xc4, 0xd9, 0x0f, 0xfc,
	0x86, 0x43, 0x57, 0x49, 0xf8, 0xb6, 0xba, 0x97, 0xaf, 0xdd, 0xec, 0x7b, 0x16, 0x47, 0xb7, 0xab,
	0x47, 0x04, 0x6b, 0xde, 0x86, 0xed, 0x13, 0xec, 0xf3, 0x80, 0x35, 0x30, 0x7b, 0xd1, 0xd6, 0xdb,
	0x9b, 0x74, 0xe9, 0xcf, 0xe7, 0xf1, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x51, 0x67, 0x7a,
	0x29, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UtilityServiceClient is the client API for UtilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UtilityServiceClient interface {
	Echo(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	EchoSpanish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	EchoChinese(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	EchoEnglish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	EchoHindi(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	EchoArabic(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	MarshalJSON(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*Bytes, error)
	MarshalYAML(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*Bytes, error)
	MarshalXML(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*Bytes, error)
	Render(ctx context.Context, in *Template, opts ...grpc.CallOption) (*Bytes, error)
}

type utilityServiceClient struct {
	cc *grpc.ClientConn
}

func NewUtilityServiceClient(cc *grpc.ClientConn) UtilityServiceClient {
	return &utilityServiceClient{cc}
}

func (c *utilityServiceClient) Echo(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.UtilityService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilityServiceClient) EchoSpanish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.UtilityService/EchoSpanish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilityServiceClient) EchoChinese(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.UtilityService/EchoChinese", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilityServiceClient) EchoEnglish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.UtilityService/EchoEnglish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilityServiceClient) EchoHindi(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.UtilityService/EchoHindi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilityServiceClient) EchoArabic(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/api.UtilityService/EchoArabic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilityServiceClient) MarshalJSON(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*Bytes, error) {
	out := new(Bytes)
	err := c.cc.Invoke(ctx, "/api.UtilityService/MarshalJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilityServiceClient) MarshalYAML(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*Bytes, error) {
	out := new(Bytes)
	err := c.cc.Invoke(ctx, "/api.UtilityService/MarshalYAML", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilityServiceClient) MarshalXML(ctx context.Context, in *Bytes, opts ...grpc.CallOption) (*Bytes, error) {
	out := new(Bytes)
	err := c.cc.Invoke(ctx, "/api.UtilityService/MarshalXML", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *utilityServiceClient) Render(ctx context.Context, in *Template, opts ...grpc.CallOption) (*Bytes, error) {
	out := new(Bytes)
	err := c.cc.Invoke(ctx, "/api.UtilityService/Render", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UtilityServiceServer is the server API for UtilityService service.
type UtilityServiceServer interface {
	Echo(context.Context, *Message) (*Message, error)
	EchoSpanish(context.Context, *Message) (*Message, error)
	EchoChinese(context.Context, *Message) (*Message, error)
	EchoEnglish(context.Context, *Message) (*Message, error)
	EchoHindi(context.Context, *Message) (*Message, error)
	EchoArabic(context.Context, *Message) (*Message, error)
	MarshalJSON(context.Context, *Bytes) (*Bytes, error)
	MarshalYAML(context.Context, *Bytes) (*Bytes, error)
	MarshalXML(context.Context, *Bytes) (*Bytes, error)
	Render(context.Context, *Template) (*Bytes, error)
}

func RegisterUtilityServiceServer(s *grpc.Server, srv UtilityServiceServer) {
	s.RegisterService(&_UtilityService_serviceDesc, srv)
}

func _UtilityService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).Echo(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _UtilityService_EchoSpanish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).EchoSpanish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/EchoSpanish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).EchoSpanish(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _UtilityService_EchoChinese_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).EchoChinese(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/EchoChinese",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).EchoChinese(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _UtilityService_EchoEnglish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).EchoEnglish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/EchoEnglish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).EchoEnglish(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _UtilityService_EchoHindi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).EchoHindi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/EchoHindi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).EchoHindi(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _UtilityService_EchoArabic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).EchoArabic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/EchoArabic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).EchoArabic(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _UtilityService_MarshalJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).MarshalJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/MarshalJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).MarshalJSON(ctx, req.(*Bytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _UtilityService_MarshalYAML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).MarshalYAML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/MarshalYAML",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).MarshalYAML(ctx, req.(*Bytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _UtilityService_MarshalXML_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).MarshalXML(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/MarshalXML",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).MarshalXML(ctx, req.(*Bytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _UtilityService_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UtilityServiceServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UtilityService/Render",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UtilityServiceServer).Render(ctx, req.(*Template))
	}
	return interceptor(ctx, in, info, handler)
}

var _UtilityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.UtilityService",
	HandlerType: (*UtilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _UtilityService_Echo_Handler,
		},
		{
			MethodName: "EchoSpanish",
			Handler:    _UtilityService_EchoSpanish_Handler,
		},
		{
			MethodName: "EchoChinese",
			Handler:    _UtilityService_EchoChinese_Handler,
		},
		{
			MethodName: "EchoEnglish",
			Handler:    _UtilityService_EchoEnglish_Handler,
		},
		{
			MethodName: "EchoHindi",
			Handler:    _UtilityService_EchoHindi_Handler,
		},
		{
			MethodName: "EchoArabic",
			Handler:    _UtilityService_EchoArabic_Handler,
		},
		{
			MethodName: "MarshalJSON",
			Handler:    _UtilityService_MarshalJSON_Handler,
		},
		{
			MethodName: "MarshalYAML",
			Handler:    _UtilityService_MarshalYAML_Handler,
		},
		{
			MethodName: "MarshalXML",
			Handler:    _UtilityService_MarshalXML_Handler,
		},
		{
			MethodName: "Render",
			Handler:    _UtilityService_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// ContactServiceClient is the client API for ContactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactServiceClient interface {
	SendSMS(ctx context.Context, in *SMS, opts ...grpc.CallOption) (*Identifier, error)
	GetSMS(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*SMSStatus, error)
	SendEmail(ctx context.Context, in *Email, opts ...grpc.CallOption) (*Identifier, error)
	SendCall(ctx context.Context, in *Call, opts ...grpc.CallOption) (*Identifier, error)
}

type contactServiceClient struct {
	cc *grpc.ClientConn
}

func NewContactServiceClient(cc *grpc.ClientConn) ContactServiceClient {
	return &contactServiceClient{cc}
}

func (c *contactServiceClient) SendSMS(ctx context.Context, in *SMS, opts ...grpc.CallOption) (*Identifier, error) {
	out := new(Identifier)
	err := c.cc.Invoke(ctx, "/api.ContactService/SendSMS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) GetSMS(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*SMSStatus, error) {
	out := new(SMSStatus)
	err := c.cc.Invoke(ctx, "/api.ContactService/GetSMS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) SendEmail(ctx context.Context, in *Email, opts ...grpc.CallOption) (*Identifier, error) {
	out := new(Identifier)
	err := c.cc.Invoke(ctx, "/api.ContactService/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) SendCall(ctx context.Context, in *Call, opts ...grpc.CallOption) (*Identifier, error) {
	out := new(Identifier)
	err := c.cc.Invoke(ctx, "/api.ContactService/SendCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServiceServer is the server API for ContactService service.
type ContactServiceServer interface {
	SendSMS(context.Context, *SMS) (*Identifier, error)
	GetSMS(context.Context, *Identifier) (*SMSStatus, error)
	SendEmail(context.Context, *Email) (*Identifier, error)
	SendCall(context.Context, *Call) (*Identifier, error)
}

func RegisterContactServiceServer(s *grpc.Server, srv ContactServiceServer) {
	s.RegisterService(&_ContactService_serviceDesc, srv)
}

func _ContactService_SendSMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).SendSMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ContactService/SendSMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).SendSMS(ctx, req.(*SMS))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_GetSMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).GetSMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ContactService/GetSMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).GetSMS(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ContactService/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).SendEmail(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_SendCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Call)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).SendCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ContactService/SendCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).SendCall(ctx, req.(*Call))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ContactService",
	HandlerType: (*ContactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSMS",
			Handler:    _ContactService_SendSMS_Handler,
		},
		{
			MethodName: "GetSMS",
			Handler:    _ContactService_GetSMS_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _ContactService_SendEmail_Handler,
		},
		{
			MethodName: "SendCall",
			Handler:    _ContactService_SendCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
