// Code generated by protoc-gen-go. DO NOT EDIT.
// source: strings/strings.proto

package strings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Format int32

const (
	Format_TEXT  Format = 0
	Format_HTML  Format = 1
	Format_BYTES Format = 2
	Format_JSON  Format = 3
	Format_YAML  Format = 4
	Format_XML   Format = 5
	Format_HCL   Format = 6
)

var Format_name = map[int32]string{
	0: "TEXT",
	1: "HTML",
	2: "BYTES",
	3: "JSON",
	4: "YAML",
	5: "XML",
	6: "HCL",
}

var Format_value = map[string]int32{
	"TEXT":  0,
	"HTML":  1,
	"BYTES": 2,
	"JSON":  3,
	"YAML":  4,
	"XML":   5,
	"HCL":   6,
}

func (x Format) String() string {
	return proto.EnumName(Format_name, int32(x))
}

func (Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{0}
}

type Text struct {
	Format               Format   `protobuf:"varint,1,opt,name=format,proto3,enum=strings.Format" json:"format,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{0}
}

func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetFormat() Format {
	if m != nil {
		return m.Format
	}
	return Format_TEXT
}

func (m *Text) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type InputString struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputString) Reset()         { *m = InputString{} }
func (m *InputString) String() string { return proto.CompactTextString(m) }
func (*InputString) ProtoMessage()    {}
func (*InputString) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{2}
}

func (m *InputString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputString.Unmarshal(m, b)
}
func (m *InputString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputString.Marshal(b, m, deterministic)
}
func (m *InputString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputString.Merge(m, src)
}
func (m *InputString) XXX_Size() int {
	return xxx_messageInfo_InputString.Size(m)
}
func (m *InputString) XXX_DiscardUnknown() {
	xxx_messageInfo_InputString.DiscardUnknown(m)
}

var xxx_messageInfo_InputString proto.InternalMessageInfo

func (m *InputString) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type RenderResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text                 *Text    `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderResponse) Reset()         { *m = RenderResponse{} }
func (m *RenderResponse) String() string { return proto.CompactTextString(m) }
func (*RenderResponse) ProtoMessage()    {}
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{3}
}

func (m *RenderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderResponse.Unmarshal(m, b)
}
func (m *RenderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderResponse.Marshal(b, m, deterministic)
}
func (m *RenderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderResponse.Merge(m, src)
}
func (m *RenderResponse) XXX_Size() int {
	return xxx_messageInfo_RenderResponse.Size(m)
}
func (m *RenderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderResponse proto.InternalMessageInfo

func (m *RenderResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RenderResponse) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *RenderResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RenderRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text                 *Text    `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderRequest) Reset()         { *m = RenderRequest{} }
func (m *RenderRequest) String() string { return proto.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()    {}
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{4}
}

func (m *RenderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderRequest.Unmarshal(m, b)
}
func (m *RenderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderRequest.Marshal(b, m, deterministic)
}
func (m *RenderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderRequest.Merge(m, src)
}
func (m *RenderRequest) XXX_Size() int {
	return xxx_messageInfo_RenderRequest.Size(m)
}
func (m *RenderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderRequest proto.InternalMessageInfo

func (m *RenderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RenderRequest) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *RenderRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReplaceRequest struct {
	Text                 *Text             `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Replacements         map[string]string `protobuf:"bytes,2,rep,name=replacements,proto3" json:"replacements,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReplaceRequest) Reset()         { *m = ReplaceRequest{} }
func (m *ReplaceRequest) String() string { return proto.CompactTextString(m) }
func (*ReplaceRequest) ProtoMessage()    {}
func (*ReplaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{5}
}

func (m *ReplaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceRequest.Unmarshal(m, b)
}
func (m *ReplaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceRequest.Marshal(b, m, deterministic)
}
func (m *ReplaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceRequest.Merge(m, src)
}
func (m *ReplaceRequest) XXX_Size() int {
	return xxx_messageInfo_ReplaceRequest.Size(m)
}
func (m *ReplaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceRequest proto.InternalMessageInfo

func (m *ReplaceRequest) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *ReplaceRequest) GetReplacements() map[string]string {
	if m != nil {
		return m.Replacements
	}
	return nil
}

type ReplaceResponse struct {
	Text                 *Text             `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Replacements         map[string]string `protobuf:"bytes,2,rep,name=replacements,proto3" json:"replacements,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReplaceResponse) Reset()         { *m = ReplaceResponse{} }
func (m *ReplaceResponse) String() string { return proto.CompactTextString(m) }
func (*ReplaceResponse) ProtoMessage()    {}
func (*ReplaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{6}
}

func (m *ReplaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceResponse.Unmarshal(m, b)
}
func (m *ReplaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceResponse.Marshal(b, m, deterministic)
}
func (m *ReplaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceResponse.Merge(m, src)
}
func (m *ReplaceResponse) XXX_Size() int {
	return xxx_messageInfo_ReplaceResponse.Size(m)
}
func (m *ReplaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceResponse proto.InternalMessageInfo

func (m *ReplaceResponse) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *ReplaceResponse) GetReplacements() map[string]string {
	if m != nil {
		return m.Replacements
	}
	return nil
}

type ExtractRequest struct {
	Text                 *Text    `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Keywords             []string `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractRequest) Reset()         { *m = ExtractRequest{} }
func (m *ExtractRequest) String() string { return proto.CompactTextString(m) }
func (*ExtractRequest) ProtoMessage()    {}
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{7}
}

func (m *ExtractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractRequest.Unmarshal(m, b)
}
func (m *ExtractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractRequest.Marshal(b, m, deterministic)
}
func (m *ExtractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractRequest.Merge(m, src)
}
func (m *ExtractRequest) XXX_Size() int {
	return xxx_messageInfo_ExtractRequest.Size(m)
}
func (m *ExtractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractRequest proto.InternalMessageInfo

func (m *ExtractRequest) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *ExtractRequest) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

type ExtractResponse struct {
	Text                 *Text    `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Keywords             []string `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtractResponse) Reset()         { *m = ExtractResponse{} }
func (m *ExtractResponse) String() string { return proto.CompactTextString(m) }
func (*ExtractResponse) ProtoMessage()    {}
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44b471cba9524d5b, []int{8}
}

func (m *ExtractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtractResponse.Unmarshal(m, b)
}
func (m *ExtractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtractResponse.Marshal(b, m, deterministic)
}
func (m *ExtractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtractResponse.Merge(m, src)
}
func (m *ExtractResponse) XXX_Size() int {
	return xxx_messageInfo_ExtractResponse.Size(m)
}
func (m *ExtractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExtractResponse proto.InternalMessageInfo

func (m *ExtractResponse) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *ExtractResponse) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func init() {
	proto.RegisterEnum("strings.Format", Format_name, Format_value)
	proto.RegisterType((*Text)(nil), "strings.Text")
	proto.RegisterType((*Empty)(nil), "strings.Empty")
	proto.RegisterType((*InputString)(nil), "strings.InputString")
	proto.RegisterType((*RenderResponse)(nil), "strings.RenderResponse")
	proto.RegisterType((*RenderRequest)(nil), "strings.RenderRequest")
	proto.RegisterType((*ReplaceRequest)(nil), "strings.ReplaceRequest")
	proto.RegisterMapType((map[string]string)(nil), "strings.ReplaceRequest.ReplacementsEntry")
	proto.RegisterType((*ReplaceResponse)(nil), "strings.ReplaceResponse")
	proto.RegisterMapType((map[string]string)(nil), "strings.ReplaceResponse.ReplacementsEntry")
	proto.RegisterType((*ExtractRequest)(nil), "strings.ExtractRequest")
	proto.RegisterType((*ExtractResponse)(nil), "strings.ExtractResponse")
}

func init() { proto.RegisterFile("strings/strings.proto", fileDescriptor_44b471cba9524d5b) }

var fileDescriptor_44b471cba9524d5b = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x71, 0xfe, 0x6e, 0xa6, 0xbb, 0xad, 0xb1, 0x40, 0x8a, 0xf6, 0x94, 0xe6, 0x42, 0xd8,
	0xc3, 0x22, 0x95, 0x0b, 0xe2, 0x82, 0x00, 0x05, 0xed, 0xa2, 0xa4, 0x45, 0x6e, 0x0e, 0x2d, 0x9c,
	0x42, 0x6b, 0x10, 0x6a, 0xe3, 0x04, 0xc7, 0x85, 0xe6, 0xf3, 0x21, 0xbe, 0x17, 0x72, 0xfe, 0x89,
	0xaa, 0x80, 0x8a, 0x04, 0xa7, 0xbe, 0x71, 0xe7, 0xfd, 0x3c, 0x2f, 0x23, 0xc3, 0xfd, 0x52, 0x8a,
	0x4f, 0xfc, 0x63, 0xf9, 0xa8, 0xfd, 0xbd, 0x2e, 0x44, 0x2e, 0x73, 0x62, 0xb7, 0xa5, 0x7f, 0x0b,
	0x46, 0xc2, 0xf6, 0x92, 0x3c, 0x00, 0xeb, 0x43, 0x2e, 0xb2, 0x54, 0xba, 0xc8, 0x43, 0xc1, 0x70,
	0x32, 0xba, 0xee, 0x0c, 0xaf, 0xea, 0x63, 0xda, 0xfe, 0x4d, 0x5c, 0xb0, 0x57, 0x39, 0x97, 0x8c,
	0x4b, 0x57, 0xf3, 0x50, 0xe0, 0xd0, 0xae, 0xf4, 0x6d, 0x30, 0xc3, 0xac, 0x90, 0x95, 0x3f, 0x86,
	0xc1, 0x2d, 0x2f, 0x76, 0x72, 0x5e, 0x13, 0x08, 0x01, 0x43, 0xb2, 0x7d, 0x03, 0x76, 0x68, 0xad,
	0xfd, 0x77, 0x30, 0xa4, 0x8c, 0xaf, 0x99, 0xa0, 0xac, 0x2c, 0x72, 0x5e, 0x32, 0xd5, 0xc5, 0xd3,
	0x8c, 0x75, 0x5d, 0x4a, 0x93, 0x71, 0xeb, 0x54, 0x17, 0x0d, 0x26, 0x17, 0xfd, 0x48, 0x6a, 0xe2,
	0x06, 0xa4, 0x6c, 0xeb, 0x54, 0xa6, 0xae, 0xee, 0xa1, 0xe0, 0x9c, 0xd6, 0xda, 0x7f, 0x0b, 0x17,
	0x1d, 0xfc, 0xf3, 0x8e, 0x95, 0xf2, 0x5f, 0xb2, 0xbf, 0x21, 0x35, 0x79, 0xb1, 0x4d, 0x57, 0xac,
	0xa3, 0x8f, 0x7f, 0xca, 0xf7, 0x1b, 0x52, 0x0c, 0xe7, 0xa2, 0x31, 0x65, 0x8c, 0xcb, 0xd2, 0xd5,
	0x3c, 0x3d, 0x18, 0x4c, 0x1e, 0xf6, 0xad, 0x87, 0xc4, 0xae, 0xac, 0x7b, 0x43, 0x2e, 0x45, 0x45,
	0x0f, 0xec, 0x97, 0xcf, 0xe0, 0xee, 0x51, 0x0b, 0xc1, 0xa0, 0x6f, 0x58, 0xd5, 0x66, 0x54, 0x92,
	0xdc, 0x03, 0xf3, 0x4b, 0xba, 0xdd, 0xb1, 0x76, 0x51, 0x4d, 0xf1, 0x54, 0x7b, 0x82, 0xfc, 0xef,
	0x08, 0x46, 0xfd, 0x9d, 0xed, 0x02, 0x4e, 0x88, 0x31, 0xfd, 0x65, 0x8c, 0xab, 0xe3, 0x18, 0x0d,
	0xf2, 0xff, 0xe7, 0x98, 0xc1, 0x30, 0xdc, 0x4b, 0x91, 0xae, 0xe4, 0x5f, 0x2c, 0xe3, 0x12, 0xce,
	0x36, 0xac, 0xfa, 0x9a, 0x8b, 0x75, 0x93, 0xc0, 0xa1, 0x7d, 0xed, 0xbf, 0x81, 0x51, 0x0f, 0x3c,
	0xfd, 0xbb, 0xfc, 0x81, 0x78, 0x15, 0x83, 0xd5, 0xbc, 0x20, 0x72, 0x06, 0x46, 0x12, 0x2e, 0x12,
	0x7c, 0x47, 0xa9, 0x9b, 0x24, 0x8e, 0x30, 0x22, 0x0e, 0x98, 0x2f, 0x96, 0x49, 0x38, 0xc7, 0x9a,
	0x3a, 0x7c, 0x3d, 0x9f, 0x4d, 0xb1, 0xae, 0xd4, 0xf2, 0x79, 0x1c, 0x61, 0x83, 0xd8, 0xa0, 0x2f,
	0xe2, 0x08, 0x9b, 0x4a, 0xdc, 0xbc, 0x8c, 0xb0, 0xf5, 0xde, 0xaa, 0xdf, 0xef, 0xe3, 0x1f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x25, 0xa4, 0xe2, 0xb1, 0xd8, 0x03, 0x00, 0x00,
}
