// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetString struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetString) Reset()         { *m = GetString{} }
func (m *GetString) String() string { return proto.CompactTextString(m) }
func (*GetString) ProtoMessage()    {}
func (*GetString) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{0}
}

func (m *GetString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetString.Unmarshal(m, b)
}
func (m *GetString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetString.Marshal(b, m, deterministic)
}
func (m *GetString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetString.Merge(m, src)
}
func (m *GetString) XXX_Size() int {
	return xxx_messageInfo_GetString.Size(m)
}
func (m *GetString) XXX_DiscardUnknown() {
	xxx_messageInfo_GetString.DiscardUnknown(m)
}

var xxx_messageInfo_GetString proto.InternalMessageInfo

func (m *GetString) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type String struct {
	This                 string   `protobuf:"bytes,1,opt,name=this,proto3" json:"this,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{1}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetThis() string {
	if m != nil {
		return m.This
	}
	return ""
}

type GetBool struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBool) Reset()         { *m = GetBool{} }
func (m *GetBool) String() string { return proto.CompactTextString(m) }
func (*GetBool) ProtoMessage()    {}
func (*GetBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{2}
}

func (m *GetBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBool.Unmarshal(m, b)
}
func (m *GetBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBool.Marshal(b, m, deterministic)
}
func (m *GetBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBool.Merge(m, src)
}
func (m *GetBool) XXX_Size() int {
	return xxx_messageInfo_GetBool.Size(m)
}
func (m *GetBool) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBool.DiscardUnknown(m)
}

var xxx_messageInfo_GetBool proto.InternalMessageInfo

func (m *GetBool) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Bool struct {
	This                 bool     `protobuf:"varint,1,opt,name=this,proto3" json:"this,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{3}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetThis() bool {
	if m != nil {
		return m.This
	}
	return false
}

type GetStrings struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStrings) Reset()         { *m = GetStrings{} }
func (m *GetStrings) String() string { return proto.CompactTextString(m) }
func (*GetStrings) ProtoMessage()    {}
func (*GetStrings) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{4}
}

func (m *GetStrings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStrings.Unmarshal(m, b)
}
func (m *GetStrings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStrings.Marshal(b, m, deterministic)
}
func (m *GetStrings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStrings.Merge(m, src)
}
func (m *GetStrings) XXX_Size() int {
	return xxx_messageInfo_GetStrings.Size(m)
}
func (m *GetStrings) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStrings.DiscardUnknown(m)
}

var xxx_messageInfo_GetStrings proto.InternalMessageInfo

func (m *GetStrings) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Strings struct {
	This                 []string `protobuf:"bytes,1,rep,name=this,proto3" json:"this,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Strings) Reset()         { *m = Strings{} }
func (m *Strings) String() string { return proto.CompactTextString(m) }
func (*Strings) ProtoMessage()    {}
func (*Strings) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{5}
}

func (m *Strings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Strings.Unmarshal(m, b)
}
func (m *Strings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Strings.Marshal(b, m, deterministic)
}
func (m *Strings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Strings.Merge(m, src)
}
func (m *Strings) XXX_Size() int {
	return xxx_messageInfo_Strings.Size(m)
}
func (m *Strings) XXX_DiscardUnknown() {
	xxx_messageInfo_Strings.DiscardUnknown(m)
}

var xxx_messageInfo_Strings proto.InternalMessageInfo

func (m *Strings) GetThis() []string {
	if m != nil {
		return m.This
	}
	return nil
}

type GetStringMap struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStringMap) Reset()         { *m = GetStringMap{} }
func (m *GetStringMap) String() string { return proto.CompactTextString(m) }
func (*GetStringMap) ProtoMessage()    {}
func (*GetStringMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{6}
}

func (m *GetStringMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStringMap.Unmarshal(m, b)
}
func (m *GetStringMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStringMap.Marshal(b, m, deterministic)
}
func (m *GetStringMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStringMap.Merge(m, src)
}
func (m *GetStringMap) XXX_Size() int {
	return xxx_messageInfo_GetStringMap.Size(m)
}
func (m *GetStringMap) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStringMap.DiscardUnknown(m)
}

var xxx_messageInfo_GetStringMap proto.InternalMessageInfo

func (m *GetStringMap) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type StringMap struct {
	This                 map[string]string `protobuf:"bytes,1,rep,name=this,proto3" json:"this,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StringMap) Reset()         { *m = StringMap{} }
func (m *StringMap) String() string { return proto.CompactTextString(m) }
func (*StringMap) ProtoMessage()    {}
func (*StringMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{7}
}

func (m *StringMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMap.Unmarshal(m, b)
}
func (m *StringMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMap.Marshal(b, m, deterministic)
}
func (m *StringMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMap.Merge(m, src)
}
func (m *StringMap) XXX_Size() int {
	return xxx_messageInfo_StringMap.Size(m)
}
func (m *StringMap) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMap.DiscardUnknown(m)
}

var xxx_messageInfo_StringMap proto.InternalMessageInfo

func (m *StringMap) GetThis() map[string]string {
	if m != nil {
		return m.This
	}
	return nil
}

type GetBoolMap struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBoolMap) Reset()         { *m = GetBoolMap{} }
func (m *GetBoolMap) String() string { return proto.CompactTextString(m) }
func (*GetBoolMap) ProtoMessage()    {}
func (*GetBoolMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{8}
}

func (m *GetBoolMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBoolMap.Unmarshal(m, b)
}
func (m *GetBoolMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBoolMap.Marshal(b, m, deterministic)
}
func (m *GetBoolMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBoolMap.Merge(m, src)
}
func (m *GetBoolMap) XXX_Size() int {
	return xxx_messageInfo_GetBoolMap.Size(m)
}
func (m *GetBoolMap) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBoolMap.DiscardUnknown(m)
}

var xxx_messageInfo_GetBoolMap proto.InternalMessageInfo

func (m *GetBoolMap) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type BoolMap struct {
	This                 map[string]bool `protobuf:"bytes,1,rep,name=this,proto3" json:"this,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BoolMap) Reset()         { *m = BoolMap{} }
func (m *BoolMap) String() string { return proto.CompactTextString(m) }
func (*BoolMap) ProtoMessage()    {}
func (*BoolMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{9}
}

func (m *BoolMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolMap.Unmarshal(m, b)
}
func (m *BoolMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolMap.Marshal(b, m, deterministic)
}
func (m *BoolMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolMap.Merge(m, src)
}
func (m *BoolMap) XXX_Size() int {
	return xxx_messageInfo_BoolMap.Size(m)
}
func (m *BoolMap) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolMap.DiscardUnknown(m)
}

var xxx_messageInfo_BoolMap proto.InternalMessageInfo

func (m *BoolMap) GetThis() map[string]bool {
	if m != nil {
		return m.This
	}
	return nil
}

type GetInt64 struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInt64) Reset()         { *m = GetInt64{} }
func (m *GetInt64) String() string { return proto.CompactTextString(m) }
func (*GetInt64) ProtoMessage()    {}
func (*GetInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{10}
}

func (m *GetInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInt64.Unmarshal(m, b)
}
func (m *GetInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInt64.Marshal(b, m, deterministic)
}
func (m *GetInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInt64.Merge(m, src)
}
func (m *GetInt64) XXX_Size() int {
	return xxx_messageInfo_GetInt64.Size(m)
}
func (m *GetInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInt64.DiscardUnknown(m)
}

var xxx_messageInfo_GetInt64 proto.InternalMessageInfo

func (m *GetInt64) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Int64 struct {
	This                 int64    `protobuf:"varint,1,opt,name=this,proto3" json:"this,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64) Reset()         { *m = Int64{} }
func (m *Int64) String() string { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()    {}
func (*Int64) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc332a44e926b360, []int{11}
}

func (m *Int64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64.Unmarshal(m, b)
}
func (m *Int64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64.Marshal(b, m, deterministic)
}
func (m *Int64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64.Merge(m, src)
}
func (m *Int64) XXX_Size() int {
	return xxx_messageInfo_Int64.Size(m)
}
func (m *Int64) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64.DiscardUnknown(m)
}

var xxx_messageInfo_Int64 proto.InternalMessageInfo

func (m *Int64) GetThis() int64 {
	if m != nil {
		return m.This
	}
	return 0
}

func init() {
	proto.RegisterType((*GetString)(nil), "config.GetString")
	proto.RegisterType((*String)(nil), "config.String")
	proto.RegisterType((*GetBool)(nil), "config.GetBool")
	proto.RegisterType((*Bool)(nil), "config.Bool")
	proto.RegisterType((*GetStrings)(nil), "config.GetStrings")
	proto.RegisterType((*Strings)(nil), "config.Strings")
	proto.RegisterType((*GetStringMap)(nil), "config.GetStringMap")
	proto.RegisterType((*StringMap)(nil), "config.StringMap")
	proto.RegisterMapType((map[string]string)(nil), "config.StringMap.ThisEntry")
	proto.RegisterType((*GetBoolMap)(nil), "config.GetBoolMap")
	proto.RegisterType((*BoolMap)(nil), "config.BoolMap")
	proto.RegisterMapType((map[string]bool)(nil), "config.BoolMap.ThisEntry")
	proto.RegisterType((*GetInt64)(nil), "config.GetInt64")
	proto.RegisterType((*Int64)(nil), "config.Int64")
}

func init() { proto.RegisterFile("config/config.proto", fileDescriptor_cc332a44e926b360) }

var fileDescriptor_cc332a44e926b360 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x2c, 0x17, 0xa7, 0x7b, 0x6a, 0x49, 0x70, 0x49, 0x51, 0x66, 0x5e, 0xba, 0x90, 0x00, 0x17, 0x73,
	0x76, 0x6a, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0xa9, 0x24, 0xc3, 0xc5, 0x06,
	0x95, 0x13, 0xe2, 0x62, 0x29, 0xc9, 0xc8, 0x2c, 0x86, 0x4a, 0x82, 0xd9, 0x4a, 0xd2, 0x5c, 0xec,
	0xee, 0xa9, 0x25, 0x4e, 0xf9, 0xf9, 0x39, 0x58, 0xb4, 0x4a, 0x71, 0xb1, 0x80, 0x65, 0x90, 0x35,
	0x72, 0x40, 0x35, 0xca, 0x71, 0x71, 0xc1, 0x6d, 0x2d, 0xc6, 0xa2, 0x57, 0x96, 0x8b, 0x1d, 0x26,
	0x89, 0xd0, 0xce, 0x0c, 0xb7, 0x57, 0x81, 0x8b, 0x07, 0xae, 0xdd, 0x37, 0xb1, 0x00, 0x8b, 0x01,
	0xa5, 0x5c, 0x9c, 0x08, 0x69, 0x7d, 0x24, 0x23, 0xb8, 0x8d, 0xa4, 0xf5, 0xa0, 0x01, 0x01, 0x57,
	0xa0, 0x17, 0x92, 0x91, 0x59, 0xec, 0x9a, 0x57, 0x52, 0x54, 0x09, 0x31, 0x5f, 0xca, 0x9c, 0x8b,
	0x13, 0x2e, 0x84, 0x69, 0xb8, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x13,
	0x58, 0x0c, 0xc2, 0xb1, 0x62, 0xb2, 0x60, 0x84, 0xfa, 0x0b, 0xe4, 0x6d, 0xec, 0xce, 0x2a, 0xe4,
	0x62, 0x87, 0x49, 0xea, 0xa2, 0x38, 0x4a, 0x12, 0xe6, 0x28, 0xa8, 0x34, 0x45, 0x4e, 0xe2, 0x40,
	0x76, 0x92, 0x0c, 0x17, 0x87, 0x7b, 0x6a, 0x89, 0x67, 0x5e, 0x89, 0x99, 0x09, 0x16, 0x07, 0x49,
	0x73, 0xb1, 0x42, 0xa4, 0x90, 0x63, 0x89, 0x19, 0x62, 0x67, 0x12, 0x1b, 0x38, 0xa9, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x74, 0xd4, 0x57, 0x95, 0x41, 0x02, 0x00, 0x00,
}
