// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	Name                 string        `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	GivenName            string        `protobuf:"bytes,7,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName           string        `protobuf:"bytes,8,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Gender               string        `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthdate            string        `protobuf:"bytes,10,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Email                string        `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	Picture              string        `protobuf:"bytes,12,opt,name=picture,proto3" json:"picture,omitempty"`
	UserMetadata         *UserMetadata `protobuf:"bytes,13,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	AppMetadata          *AppMetadata  `protobuf:"bytes,14,opt,name=app_metadata,json=appMetadata,proto3" json:"app_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *UserInfo) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *UserInfo) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserInfo) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *UserInfo) GetUserMetadata() *UserMetadata {
	if m != nil {
		return m.UserMetadata
	}
	return nil
}

func (m *UserInfo) GetAppMetadata() *AppMetadata {
	if m != nil {
		return m.AppMetadata
	}
	return nil
}

type UserMetadata struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	PreferredContact     string   `protobuf:"bytes,2,opt,name=preferred_contact,json=preferredContact,proto3" json:"preferred_contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMetadata) Reset()         { *m = UserMetadata{} }
func (m *UserMetadata) String() string { return proto.CompactTextString(m) }
func (*UserMetadata) ProtoMessage()    {}
func (*UserMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *UserMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMetadata.Unmarshal(m, b)
}
func (m *UserMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMetadata.Marshal(b, m, deterministic)
}
func (m *UserMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMetadata.Merge(m, src)
}
func (m *UserMetadata) XXX_Size() int {
	return xxx_messageInfo_UserMetadata.Size(m)
}
func (m *UserMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_UserMetadata proto.InternalMessageInfo

func (m *UserMetadata) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserMetadata) GetPreferredContact() string {
	if m != nil {
		return m.PreferredContact
	}
	return ""
}

type AppMetadata struct {
	Plan                 string   `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	PayToken             string   `protobuf:"bytes,2,opt,name=pay_token,json=payToken,proto3" json:"pay_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppMetadata) Reset()         { *m = AppMetadata{} }
func (m *AppMetadata) String() string { return proto.CompactTextString(m) }
func (*AppMetadata) ProtoMessage()    {}
func (*AppMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *AppMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMetadata.Unmarshal(m, b)
}
func (m *AppMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMetadata.Marshal(b, m, deterministic)
}
func (m *AppMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMetadata.Merge(m, src)
}
func (m *AppMetadata) XXX_Size() int {
	return xxx_messageInfo_AppMetadata.Size(m)
}
func (m *AppMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_AppMetadata proto.InternalMessageInfo

func (m *AppMetadata) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *AppMetadata) GetPayToken() string {
	if m != nil {
		return m.PayToken
	}
	return ""
}

type AccessToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type IDToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDToken) Reset()         { *m = IDToken{} }
func (m *IDToken) String() string { return proto.CompactTextString(m) }
func (*IDToken) ProtoMessage()    {}
func (*IDToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *IDToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDToken.Unmarshal(m, b)
}
func (m *IDToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDToken.Marshal(b, m, deterministic)
}
func (m *IDToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDToken.Merge(m, src)
}
func (m *IDToken) XXX_Size() int {
	return xxx_messageInfo_IDToken.Size(m)
}
func (m *IDToken) XXX_DiscardUnknown() {
	xxx_messageInfo_IDToken.DiscardUnknown(m)
}

var xxx_messageInfo_IDToken proto.InternalMessageInfo

func (m *IDToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshToken) Reset()         { *m = RefreshToken{} }
func (m *RefreshToken) String() string { return proto.CompactTextString(m) }
func (*RefreshToken) ProtoMessage()    {}
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *RefreshToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshToken.Unmarshal(m, b)
}
func (m *RefreshToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshToken.Marshal(b, m, deterministic)
}
func (m *RefreshToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshToken.Merge(m, src)
}
func (m *RefreshToken) XXX_Size() int {
	return xxx_messageInfo_RefreshToken.Size(m)
}
func (m *RefreshToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshToken.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshToken proto.InternalMessageInfo

func (m *RefreshToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Tokens struct {
	Id                   *IDToken      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Access               *AccessToken  `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`
	Refresh              *RefreshToken `protobuf:"bytes,3,opt,name=refresh,proto3" json:"refresh,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Tokens) Reset()         { *m = Tokens{} }
func (m *Tokens) String() string { return proto.CompactTextString(m) }
func (*Tokens) ProtoMessage()    {}
func (*Tokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *Tokens) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tokens.Unmarshal(m, b)
}
func (m *Tokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tokens.Marshal(b, m, deterministic)
}
func (m *Tokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tokens.Merge(m, src)
}
func (m *Tokens) XXX_Size() int {
	return xxx_messageInfo_Tokens.Size(m)
}
func (m *Tokens) XXX_DiscardUnknown() {
	xxx_messageInfo_Tokens.DiscardUnknown(m)
}

var xxx_messageInfo_Tokens proto.InternalMessageInfo

func (m *Tokens) GetId() *IDToken {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Tokens) GetAccess() *AccessToken {
	if m != nil {
		return m.Access
	}
	return nil
}

func (m *Tokens) GetRefresh() *RefreshToken {
	if m != nil {
		return m.Refresh
	}
	return nil
}

type Paths struct {
	Home                 string   `protobuf:"bytes,1,opt,name=home,proto3" json:"home,omitempty"`
	Dashboard            string   `protobuf:"bytes,2,opt,name=dashboard,proto3" json:"dashboard,omitempty"`
	Settings             string   `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	Logout               string   `protobuf:"bytes,4,opt,name=logout,proto3" json:"logout,omitempty"`
	Callback             string   `protobuf:"bytes,5,opt,name=callback,proto3" json:"callback,omitempty"`
	Login                string   `protobuf:"bytes,6,opt,name=login,proto3" json:"login,omitempty"`
	Subscribe            string   `protobuf:"bytes,7,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	Unsubscribe          string   `protobuf:"bytes,8,opt,name=unsubscribe,proto3" json:"unsubscribe,omitempty"`
	Faq                  string   `protobuf:"bytes,9,opt,name=faq,proto3" json:"faq,omitempty"`
	Support              string   `protobuf:"bytes,10,opt,name=support,proto3" json:"support,omitempty"`
	Terms                string   `protobuf:"bytes,11,opt,name=terms,proto3" json:"terms,omitempty"`
	Privacy              string   `protobuf:"bytes,12,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Debug                string   `protobuf:"bytes,13,opt,name=debug,proto3" json:"debug,omitempty"`
	Blog                 string   `protobuf:"bytes,14,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paths) Reset()         { *m = Paths{} }
func (m *Paths) String() string { return proto.CompactTextString(m) }
func (*Paths) ProtoMessage()    {}
func (*Paths) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *Paths) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paths.Unmarshal(m, b)
}
func (m *Paths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paths.Marshal(b, m, deterministic)
}
func (m *Paths) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paths.Merge(m, src)
}
func (m *Paths) XXX_Size() int {
	return xxx_messageInfo_Paths.Size(m)
}
func (m *Paths) XXX_DiscardUnknown() {
	xxx_messageInfo_Paths.DiscardUnknown(m)
}

var xxx_messageInfo_Paths proto.InternalMessageInfo

func (m *Paths) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *Paths) GetDashboard() string {
	if m != nil {
		return m.Dashboard
	}
	return ""
}

func (m *Paths) GetSettings() string {
	if m != nil {
		return m.Settings
	}
	return ""
}

func (m *Paths) GetLogout() string {
	if m != nil {
		return m.Logout
	}
	return ""
}

func (m *Paths) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

func (m *Paths) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Paths) GetSubscribe() string {
	if m != nil {
		return m.Subscribe
	}
	return ""
}

func (m *Paths) GetUnsubscribe() string {
	if m != nil {
		return m.Unsubscribe
	}
	return ""
}

func (m *Paths) GetFaq() string {
	if m != nil {
		return m.Faq
	}
	return ""
}

func (m *Paths) GetSupport() string {
	if m != nil {
		return m.Support
	}
	return ""
}

func (m *Paths) GetTerms() string {
	if m != nil {
		return m.Terms
	}
	return ""
}

func (m *Paths) GetPrivacy() string {
	if m != nil {
		return m.Privacy
	}
	return ""
}

func (m *Paths) GetDebug() string {
	if m != nil {
		return m.Debug
	}
	return ""
}

func (m *Paths) GetBlog() string {
	if m != nil {
		return m.Blog
	}
	return ""
}

type CreateCustomerRequest struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type CreateCustomerResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

func (m *CreateCustomerResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "api.UserInfo")
	proto.RegisterType((*UserMetadata)(nil), "api.UserMetadata")
	proto.RegisterType((*AppMetadata)(nil), "api.AppMetadata")
	proto.RegisterType((*AccessToken)(nil), "api.AccessToken")
	proto.RegisterType((*IDToken)(nil), "api.IDToken")
	proto.RegisterType((*RefreshToken)(nil), "api.RefreshToken")
	proto.RegisterType((*Tokens)(nil), "api.Tokens")
	proto.RegisterType((*Paths)(nil), "api.Paths")
	proto.RegisterType((*CreateCustomerRequest)(nil), "api.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "api.CreateCustomerResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 676 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0xd2, 0x36, 0x89, 0xc7, 0x49, 0x69, 0x57, 0x50, 0x59, 0x69, 0x51, 0x2b, 0xc3, 0x21,
	0x6a, 0xa5, 0x46, 0xb4, 0x12, 0x07, 0x0e, 0x48, 0x55, 0xb8, 0xf4, 0x00, 0x02, 0x03, 0xe7, 0x68,
	0x6d, 0x6f, 0x9c, 0x55, 0x9d, 0xdd, 0xed, 0xee, 0x3a, 0x52, 0x0e, 0x5c, 0x78, 0x05, 0x9e, 0x84,
	0x67, 0xe1, 0x15, 0xe0, 0x3d, 0xd0, 0xce, 0x3a, 0x4e, 0x40, 0x55, 0x6f, 0xf3, 0xcd, 0x37, 0x7f,
	0x9e, 0x9d, 0xcf, 0x10, 0x50, 0xc5, 0x2f, 0x95, 0x96, 0x56, 0x92, 0x1d, 0xaa, 0xf8, 0xf0, 0xa4,
	0x90, 0xb2, 0x28, 0xd9, 0x98, 0x2a, 0x3e, 0xa6, 0x42, 0x48, 0x4b, 0x2d, 0x97, 0xc2, 0xf8, 0x90,
	0xf8, 0x67, 0x1b, 0x7a, 0x5f, 0x0d, 0xd3, 0xb7, 0x62, 0x26, 0x09, 0x81, 0x5d, 0x41, 0x17, 0x2c,
	0xea, 0x9c, 0xb5, 0x46, 0x41, 0x82, 0x36, 0x79, 0x0e, 0x50, 0xf0, 0x25, 0x13, 0x53, 0x64, 0xba,
	0xc8, 0x04, 0xe8, 0xf9, 0xe0, 0xe8, 0x53, 0x08, 0x67, 0x74, 0xc1, 0xcb, 0x95, 0xe7, 0x7b, 0xc8,
	0x83, 0x77, 0x61, 0xc0, 0x11, 0x74, 0x0a, 0x26, 0x72, 0xa6, 0xa3, 0x00, 0xb9, 0x1a, 0x91, 0x13,
	0x08, 0x52, 0xae, 0xed, 0x3c, 0xa7, 0x96, 0x45, 0xe0, 0xcb, 0x36, 0x0e, 0xf2, 0x14, 0xf6, 0xd8,
	0x82, 0xf2, 0x32, 0x0a, 0x91, 0xf1, 0x80, 0x44, 0xd0, 0x55, 0x3c, 0xb3, 0x95, 0x66, 0x51, 0x1f,
	0xfd, 0x6b, 0x48, 0x5e, 0xc3, 0xa0, 0x32, 0x4c, 0x4f, 0x17, 0xcc, 0xd2, 0x9c, 0x5a, 0x1a, 0x0d,
	0xce, 0x5a, 0xa3, 0xf0, 0xea, 0xf0, 0xd2, 0x2d, 0xc3, 0x7d, 0xdf, 0xfb, 0x9a, 0x48, 0xfa, 0xd5,
	0x16, 0x22, 0xd7, 0xd0, 0xa7, 0x4a, 0x6d, 0xd2, 0xf6, 0x31, 0xed, 0x00, 0xd3, 0x6e, 0x94, 0x6a,
	0xb2, 0x42, 0xba, 0x01, 0xf1, 0x27, 0xe8, 0x6f, 0x97, 0x74, 0xc3, 0xaa, 0xb9, 0x14, 0x2c, 0x6a,
	0xf9, 0x61, 0x11, 0x90, 0x0b, 0x38, 0x54, 0x9a, 0xcd, 0x98, 0xd6, 0x2c, 0x9f, 0x66, 0x52, 0x58,
	0x9a, 0xd9, 0xa8, 0x8d, 0x11, 0x07, 0x0d, 0x31, 0xf1, 0xfe, 0xf8, 0x2d, 0x84, 0x5b, 0xed, 0xdc,
	0x43, 0xa8, 0x92, 0x8a, 0xba, 0x20, 0xda, 0xe4, 0x18, 0x02, 0x45, 0x57, 0x53, 0x2b, 0xef, 0x98,
	0xa8, 0xeb, 0xf4, 0x14, 0x5d, 0x7d, 0x71, 0x38, 0x7e, 0x01, 0xe1, 0x4d, 0x96, 0x31, 0x63, 0x10,
	0xba, 0x89, 0x7c, 0x5c, 0x3d, 0x11, 0x82, 0xf8, 0x14, 0xba, 0xb7, 0xef, 0x1e, 0x0b, 0x78, 0x09,
	0xfd, 0x84, 0xcd, 0x34, 0x33, 0xf3, 0xc7, 0xa2, 0xbe, 0x41, 0x07, 0x69, 0x43, 0x4e, 0xa0, 0xcd,
	0x73, 0x24, 0xc3, 0xab, 0x3e, 0xee, 0xac, 0xae, 0x9f, 0xb4, 0x79, 0x4e, 0x46, 0xd0, 0xa1, 0x38,
	0x13, 0x4e, 0xdb, 0x6c, 0x75, 0x33, 0x66, 0x52, 0xf3, 0xe4, 0x02, 0xba, 0xda, 0xf7, 0x8d, 0x76,
	0xb6, 0xde, 0x6d, 0x7b, 0x96, 0x64, 0x1d, 0x11, 0xff, 0x69, 0xc3, 0xde, 0x47, 0x6a, 0xe7, 0xc6,
	0x6d, 0x69, 0x2e, 0x17, 0xeb, 0xb5, 0xa3, 0xed, 0xce, 0x2a, 0xa7, 0x66, 0x9e, 0x4a, 0xaa, 0xf3,
	0x7a, 0x4b, 0x1b, 0x07, 0x19, 0x42, 0xcf, 0x30, 0x6b, 0xb9, 0x28, 0x0c, 0x76, 0x0a, 0x92, 0x06,
	0xbb, 0x43, 0x2d, 0x65, 0x21, 0x2b, 0x1b, 0xed, 0xfa, 0x43, 0xf5, 0xc8, 0xe5, 0x64, 0xb4, 0x2c,
	0x53, 0x9a, 0xdd, 0x45, 0x7b, 0x3e, 0x67, 0x8d, 0xdd, 0x82, 0x4a, 0x59, 0x70, 0x51, 0x2b, 0xc6,
	0x03, 0x37, 0x83, 0xa9, 0x52, 0x93, 0x69, 0x9e, 0x36, 0x8a, 0x69, 0x1c, 0xe4, 0x0c, 0xc2, 0x4a,
	0x6c, 0x78, 0xaf, 0x98, 0x6d, 0x17, 0x39, 0x80, 0x9d, 0x19, 0xbd, 0xaf, 0xf5, 0xe2, 0x4c, 0x77,
	0xf8, 0xa6, 0x52, 0x4a, 0x6a, 0x5b, 0x4b, 0x65, 0x0d, 0xf1, 0x89, 0x98, 0x5e, 0x98, 0xb5, 0x50,
	0x10, 0xa0, 0x50, 0x34, 0x5f, 0xd2, 0x6c, 0xd5, 0x08, 0xc5, 0x43, 0x17, 0x9f, 0xb3, 0xb4, 0x2a,
	0x50, 0x20, 0x41, 0xe2, 0x81, 0xdb, 0x64, 0x5a, 0xca, 0x02, 0xcf, 0x3f, 0x48, 0xd0, 0x8e, 0x27,
	0xf0, 0x6c, 0xa2, 0x19, 0xb5, 0x6c, 0x52, 0x19, 0x2b, 0x17, 0x4c, 0x27, 0xec, 0xbe, 0x62, 0xc6,
	0x92, 0x73, 0x08, 0x50, 0x6b, 0x5c, 0xcc, 0x64, 0xfd, 0xf8, 0x83, 0x46, 0x67, 0xee, 0x3f, 0x92,
	0xf4, 0xaa, 0xda, 0x8a, 0x47, 0x70, 0xf4, 0x7f, 0x11, 0xa3, 0xa4, 0x30, 0x8c, 0xec, 0x37, 0xb7,
	0x13, 0xb8, 0x6b, 0xb9, 0x5a, 0xc2, 0x93, 0x75, 0xcc, 0x67, 0xa6, 0x97, 0x3c, 0x63, 0x24, 0x83,
	0xfd, 0x7f, 0x93, 0xc9, 0x10, 0xfb, 0x3c, 0x38, 0xd6, 0xf0, 0xf8, 0x41, 0xce, 0x77, 0x8b, 0xa3,
	0xef, 0xbf, 0x7e, 0xff, 0x68, 0x93, 0x78, 0x30, 0x5e, 0xbe, 0x1a, 0x67, 0x35, 0x6b, 0xde, 0xb4,
	0xce, 0xd3, 0x0e, 0xfe, 0x07, 0xaf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xf3, 0x1a, 0xda,
	0x37, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error) {
	out := new(CreateCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.CustomerService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerResponse, error)
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CustomerService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _CustomerService_CreateCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
