// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	Name                 string        `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	GivenName            string        `protobuf:"bytes,7,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName           string        `protobuf:"bytes,8,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Gender               string        `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthdate            string        `protobuf:"bytes,10,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Email                string        `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	Picture              string        `protobuf:"bytes,12,opt,name=picture,proto3" json:"picture,omitempty"`
	UserMetadata         *UserMetadata `protobuf:"bytes,13,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	AppMetadata          *AppMetadata  `protobuf:"bytes,14,opt,name=app_metadata,json=appMetadata,proto3" json:"app_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *UserInfo) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *UserInfo) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserInfo) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *UserInfo) GetUserMetadata() *UserMetadata {
	if m != nil {
		return m.UserMetadata
	}
	return nil
}

func (m *UserInfo) GetAppMetadata() *AppMetadata {
	if m != nil {
		return m.AppMetadata
	}
	return nil
}

type UserMetadata struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	PreferredContact     string   `protobuf:"bytes,2,opt,name=preferred_contact,json=preferredContact,proto3" json:"preferred_contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMetadata) Reset()         { *m = UserMetadata{} }
func (m *UserMetadata) String() string { return proto.CompactTextString(m) }
func (*UserMetadata) ProtoMessage()    {}
func (*UserMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *UserMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMetadata.Unmarshal(m, b)
}
func (m *UserMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMetadata.Marshal(b, m, deterministic)
}
func (m *UserMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMetadata.Merge(m, src)
}
func (m *UserMetadata) XXX_Size() int {
	return xxx_messageInfo_UserMetadata.Size(m)
}
func (m *UserMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_UserMetadata proto.InternalMessageInfo

func (m *UserMetadata) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserMetadata) GetPreferredContact() string {
	if m != nil {
		return m.PreferredContact
	}
	return ""
}

type AppMetadata struct {
	Plan                 string   `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	PayToken             string   `protobuf:"bytes,2,opt,name=pay_token,json=payToken,proto3" json:"pay_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppMetadata) Reset()         { *m = AppMetadata{} }
func (m *AppMetadata) String() string { return proto.CompactTextString(m) }
func (*AppMetadata) ProtoMessage()    {}
func (*AppMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *AppMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMetadata.Unmarshal(m, b)
}
func (m *AppMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMetadata.Marshal(b, m, deterministic)
}
func (m *AppMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMetadata.Merge(m, src)
}
func (m *AppMetadata) XXX_Size() int {
	return xxx_messageInfo_AppMetadata.Size(m)
}
func (m *AppMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_AppMetadata proto.InternalMessageInfo

func (m *AppMetadata) GetPlan() string {
	if m != nil {
		return m.Plan
	}
	return ""
}

func (m *AppMetadata) GetPayToken() string {
	if m != nil {
		return m.PayToken
	}
	return ""
}

type AccessToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type IDToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDToken) Reset()         { *m = IDToken{} }
func (m *IDToken) String() string { return proto.CompactTextString(m) }
func (*IDToken) ProtoMessage()    {}
func (*IDToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *IDToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDToken.Unmarshal(m, b)
}
func (m *IDToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDToken.Marshal(b, m, deterministic)
}
func (m *IDToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDToken.Merge(m, src)
}
func (m *IDToken) XXX_Size() int {
	return xxx_messageInfo_IDToken.Size(m)
}
func (m *IDToken) XXX_DiscardUnknown() {
	xxx_messageInfo_IDToken.DiscardUnknown(m)
}

var xxx_messageInfo_IDToken proto.InternalMessageInfo

func (m *IDToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshToken) Reset()         { *m = RefreshToken{} }
func (m *RefreshToken) String() string { return proto.CompactTextString(m) }
func (*RefreshToken) ProtoMessage()    {}
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *RefreshToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshToken.Unmarshal(m, b)
}
func (m *RefreshToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshToken.Marshal(b, m, deterministic)
}
func (m *RefreshToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshToken.Merge(m, src)
}
func (m *RefreshToken) XXX_Size() int {
	return xxx_messageInfo_RefreshToken.Size(m)
}
func (m *RefreshToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshToken.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshToken proto.InternalMessageInfo

func (m *RefreshToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Tokens struct {
	Id                   *IDToken      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Access               *AccessToken  `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`
	Refresh              *RefreshToken `protobuf:"bytes,3,opt,name=refresh,proto3" json:"refresh,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Tokens) Reset()         { *m = Tokens{} }
func (m *Tokens) String() string { return proto.CompactTextString(m) }
func (*Tokens) ProtoMessage()    {}
func (*Tokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *Tokens) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tokens.Unmarshal(m, b)
}
func (m *Tokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tokens.Marshal(b, m, deterministic)
}
func (m *Tokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tokens.Merge(m, src)
}
func (m *Tokens) XXX_Size() int {
	return xxx_messageInfo_Tokens.Size(m)
}
func (m *Tokens) XXX_DiscardUnknown() {
	xxx_messageInfo_Tokens.DiscardUnknown(m)
}

var xxx_messageInfo_Tokens proto.InternalMessageInfo

func (m *Tokens) GetId() *IDToken {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Tokens) GetAccess() *AccessToken {
	if m != nil {
		return m.Access
	}
	return nil
}

func (m *Tokens) GetRefresh() *RefreshToken {
	if m != nil {
		return m.Refresh
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "api.UserInfo")
	proto.RegisterType((*UserMetadata)(nil), "api.UserMetadata")
	proto.RegisterType((*AppMetadata)(nil), "api.AppMetadata")
	proto.RegisterType((*AccessToken)(nil), "api.AccessToken")
	proto.RegisterType((*IDToken)(nil), "api.IDToken")
	proto.RegisterType((*RefreshToken)(nil), "api.RefreshToken")
	proto.RegisterType((*Tokens)(nil), "api.Tokens")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0xb1, 0xd2, 0x4a, 0xd6, 0x48, 0x29, 0xc9, 0x52, 0xca, 0x42, 0x53, 0x12, 0xd4, 0x1e,
	0x0c, 0x81, 0x1c, 0x62, 0xe8, 0xb1, 0x60, 0xda, 0x8b, 0x0f, 0x2d, 0x54, 0xb4, 0x67, 0x31, 0x96,
	0x46, 0xf6, 0x52, 0x6b, 0xb5, 0xac, 0xd6, 0x05, 0x1f, 0xfa, 0xa1, 0xfa, 0x0d, 0x83, 0x66, 0x65,
	0x59, 0x27, 0xdf, 0xf6, 0xcd, 0xef, 0xcd, 0xec, 0xdb, 0x3f, 0x10, 0xa3, 0x51, 0x4f, 0xc6, 0xb6,
	0xae, 0x15, 0x57, 0x68, 0x54, 0xf6, 0x3f, 0x80, 0xf9, 0xef, 0x8e, 0xec, 0x5a, 0xd7, 0xad, 0x10,
	0xf0, 0x4a, 0x63, 0x43, 0x32, 0x7c, 0x98, 0x2d, 0xe2, 0x9c, 0xd7, 0xe2, 0x03, 0xc0, 0x56, 0xfd,
	0x25, 0x5d, 0x30, 0x89, 0x98, 0xc4, 0x5c, 0xf9, 0xd1, 0xe3, 0x7b, 0x48, 0x6a, 0x6c, 0xd4, 0xfe,
	0xe8, 0xf9, 0x9c, 0x39, 0xf8, 0x12, 0x1b, 0xde, 0x41, 0xb8, 0x25, 0x5d, 0x91, 0x95, 0x31, 0xb3,
	0x41, 0x89, 0x3b, 0x88, 0x37, 0xca, 0xba, 0x5d, 0x85, 0x8e, 0x24, 0xf8, 0xb1, 0x63, 0x41, 0xbc,
	0x85, 0xd7, 0xd4, 0xa0, 0xda, 0xcb, 0x84, 0x89, 0x17, 0x42, 0x42, 0x64, 0x54, 0xe9, 0x0e, 0x96,
	0x64, 0xca, 0xf5, 0x93, 0x14, 0x9f, 0xe1, 0xfa, 0xd0, 0x91, 0x2d, 0x1a, 0x72, 0x58, 0xa1, 0x43,
	0x79, 0xfd, 0x30, 0x5b, 0x24, 0xcf, 0xb7, 0x4f, 0xfd, 0x71, 0xfb, 0xf3, 0x7d, 0x1f, 0x40, 0x9e,
	0x1e, 0x26, 0x4a, 0x2c, 0x21, 0x45, 0x63, 0xce, 0x6d, 0x6f, 0xb8, 0xed, 0x86, 0xdb, 0x56, 0xc6,
	0x8c, 0x5d, 0x09, 0x9e, 0x45, 0xf6, 0x13, 0xd2, 0xe9, 0xc8, 0x3e, 0xac, 0xd9, 0xb5, 0x9a, 0xe4,
	0xcc, 0x87, 0x65, 0x21, 0x1e, 0xe1, 0xd6, 0x58, 0xaa, 0xc9, 0x5a, 0xaa, 0x8a, 0xb2, 0xd5, 0x0e,
	0x4b, 0x27, 0x03, 0x76, 0xdc, 0x8c, 0xe0, 0xab, 0xaf, 0x67, 0x5f, 0x20, 0x99, 0x6c, 0xd7, 0x3f,
	0x84, 0xd9, 0xa3, 0x1e, 0x06, 0xf2, 0x5a, 0xbc, 0x87, 0xd8, 0xe0, 0xb1, 0x70, 0xed, 0x1f, 0xd2,
	0xc3, 0x9c, 0xb9, 0xc1, 0xe3, 0xaf, 0x5e, 0x67, 0x1f, 0x21, 0x59, 0x95, 0x25, 0x75, 0x1d, 0xcb,
	0x3e, 0x91, 0xf7, 0x0d, 0x89, 0x58, 0x64, 0xf7, 0x10, 0xad, 0xbf, 0x5d, 0x32, 0x7c, 0x82, 0x34,
	0xa7, 0xda, 0x52, 0xb7, 0xbb, 0xe4, 0xfa, 0x07, 0x21, 0xe3, 0x4e, 0xdc, 0x41, 0xa0, 0x2a, 0x86,
	0xc9, 0x73, 0xca, 0x77, 0x36, 0xcc, 0xcf, 0x03, 0x55, 0x89, 0x05, 0x84, 0xc8, 0x99, 0x38, 0xed,
	0x78, 0xab, 0xe7, 0x98, 0xf9, 0xc0, 0xc5, 0x23, 0x44, 0xd6, 0xef, 0x2b, 0xaf, 0x26, 0xef, 0x36,
	0xcd, 0x92, 0x9f, 0x1c, 0x9b, 0x90, 0x7f, 0xef, 0xf2, 0x25, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x29,
	0xc7, 0x8e, 0xca, 0x02, 0x00, 0x00,
}
