// Code generated by protoc-gen-go. DO NOT EDIT.
// source: documents/documents.proto

package documents

import (
	fmt "fmt"
	time "github.com/autom8ter/api/sdk/go/time"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDoc struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateDoc) Reset()         { *m = CreateDoc{} }
func (m *CreateDoc) String() string { return proto.CompactTextString(m) }
func (*CreateDoc) ProtoMessage()    {}
func (*CreateDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d307ff86905cec7, []int{0}
}

func (m *CreateDoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDoc.Unmarshal(m, b)
}
func (m *CreateDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDoc.Marshal(b, m, deterministic)
}
func (m *CreateDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDoc.Merge(m, src)
}
func (m *CreateDoc) XXX_Size() int {
	return xxx_messageInfo_CreateDoc.Size(m)
}
func (m *CreateDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDoc.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDoc proto.InternalMessageInfo

func (m *CreateDoc) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type Document struct {
	Path                 string            `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id                   string            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Parent               *Collection       `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Data                 map[string][]byte `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Meta                 map[string]string `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tracker              *time.Tracker     `protobuf:"bytes,6,opt,name=tracker,proto3" json:"tracker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d307ff86905cec7, []int{1}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Document) GetParent() *Collection {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Document) GetData() map[string][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Document) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Document) GetTracker() *time.Tracker {
	if m != nil {
		return m.Tracker
	}
	return nil
}

type Documents struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Documents) Reset()         { *m = Documents{} }
func (m *Documents) String() string { return proto.CompactTextString(m) }
func (*Documents) ProtoMessage()    {}
func (*Documents) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d307ff86905cec7, []int{2}
}

func (m *Documents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Documents.Unmarshal(m, b)
}
func (m *Documents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Documents.Marshal(b, m, deterministic)
}
func (m *Documents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Documents.Merge(m, src)
}
func (m *Documents) XXX_Size() int {
	return xxx_messageInfo_Documents.Size(m)
}
func (m *Documents) XXX_DiscardUnknown() {
	xxx_messageInfo_Documents.DiscardUnknown(m)
}

var xxx_messageInfo_Documents proto.InternalMessageInfo

func (m *Documents) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type Collections struct {
	Collections          []*Collection `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Collections) Reset()         { *m = Collections{} }
func (m *Collections) String() string { return proto.CompactTextString(m) }
func (*Collections) ProtoMessage()    {}
func (*Collections) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d307ff86905cec7, []int{3}
}

func (m *Collections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collections.Unmarshal(m, b)
}
func (m *Collections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collections.Marshal(b, m, deterministic)
}
func (m *Collections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collections.Merge(m, src)
}
func (m *Collections) XXX_Size() int {
	return xxx_messageInfo_Collections.Size(m)
}
func (m *Collections) XXX_DiscardUnknown() {
	xxx_messageInfo_Collections.DiscardUnknown(m)
}

var xxx_messageInfo_Collections proto.InternalMessageInfo

func (m *Collections) GetCollections() []*Collection {
	if m != nil {
		return m.Collections
	}
	return nil
}

type Collection struct {
	Path                 string    `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id                   string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Parent               *Document `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d307ff86905cec7, []int{4}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Collection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Collection) GetParent() *Document {
	if m != nil {
		return m.Parent
	}
	return nil
}

type Request struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d307ff86905cec7, []int{5}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Requests struct {
	Requests             []*Request `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Requests) Reset()         { *m = Requests{} }
func (m *Requests) String() string { return proto.CompactTextString(m) }
func (*Requests) ProtoMessage()    {}
func (*Requests) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d307ff86905cec7, []int{6}
}

func (m *Requests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requests.Unmarshal(m, b)
}
func (m *Requests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requests.Marshal(b, m, deterministic)
}
func (m *Requests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requests.Merge(m, src)
}
func (m *Requests) XXX_Size() int {
	return xxx_messageInfo_Requests.Size(m)
}
func (m *Requests) XXX_DiscardUnknown() {
	xxx_messageInfo_Requests.DiscardUnknown(m)
}

var xxx_messageInfo_Requests proto.InternalMessageInfo

func (m *Requests) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateDoc)(nil), "documents.CreateDoc")
	proto.RegisterType((*Document)(nil), "documents.Document")
	proto.RegisterMapType((map[string][]byte)(nil), "documents.Document.DataEntry")
	proto.RegisterMapType((map[string]string)(nil), "documents.Document.MetaEntry")
	proto.RegisterType((*Documents)(nil), "documents.Documents")
	proto.RegisterType((*Collections)(nil), "documents.Collections")
	proto.RegisterType((*Collection)(nil), "documents.Collection")
	proto.RegisterType((*Request)(nil), "documents.Request")
	proto.RegisterType((*Requests)(nil), "documents.Requests")
}

func init() { proto.RegisterFile("documents/documents.proto", fileDescriptor_5d307ff86905cec7) }

var fileDescriptor_5d307ff86905cec7 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xfa, 0x96, 0x4c, 0x9e, 0x47, 0x65, 0x54, 0x88, 0x05, 0xa1, 0xec, 0xc5, 0x82,
	0x34, 0xa5, 0xf5, 0x50, 0x29, 0xe2, 0xa5, 0xd5, 0x9b, 0x97, 0xc5, 0xab, 0x87, 0x35, 0x59, 0x30,
	0xf4, 0x25, 0x75, 0xb3, 0x15, 0xfa, 0x65, 0xfd, 0x2c, 0x92, 0xed, 0x66, 0x37, 0x48, 0x8a, 0xbd,
	0x2c, 0xb3, 0x33, 0xbf, 0xff, 0xbc, 0xec, 0x2c, 0x5c, 0x25, 0x59, 0xbc, 0x5d, 0xf1, 0xb5, 0xcc,
	0x87, 0xc6, 0x8a, 0x36, 0x22, 0x93, 0x19, 0xfa, 0xc6, 0xd1, 0x3d, 0x95, 0xe9, 0x8a, 0x0f, 0x8b,
	0x63, 0x1f, 0x23, 0x0f, 0xe0, 0xcf, 0x04, 0x67, 0x92, 0xcf, 0xb3, 0x18, 0x87, 0xe0, 0x95, 0x68,
	0xe8, 0xf4, 0x9c, 0x7e, 0x30, 0x3e, 0x8f, 0x6c, 0xb2, 0xb9, 0xb6, 0xa8, 0x81, 0xc8, 0xb7, 0x0b,
	0x5e, 0xe9, 0x46, 0x84, 0xe6, 0x86, 0xc9, 0x0f, 0xa5, 0xf4, 0xa9, 0xb2, 0xf1, 0x04, 0xdc, 0x34,
	0x09, 0x5d, 0xe5, 0x71, 0xd3, 0x04, 0x07, 0xd0, 0xde, 0x30, 0x51, 0xe4, 0x6f, 0xa8, 0xfc, 0x97,
	0x95, 0xfc, 0xb3, 0x6c, 0xb9, 0xe4, 0xb1, 0x4c, 0xb3, 0x35, 0xd5, 0x10, 0x8e, 0xa0, 0x99, 0x30,
	0xc9, 0xc2, 0x66, 0xaf, 0xd1, 0x0f, 0xc6, 0xd7, 0x35, 0xcd, 0x44, 0x73, 0x26, 0xd9, 0xd3, 0x5a,
	0x8a, 0x1d, 0x55, 0x68, 0x21, 0x59, 0x71, 0xc9, 0xc2, 0xd6, 0x61, 0xc9, 0x0b, 0x37, 0x92, 0x02,
	0xc5, 0x1b, 0xe8, 0x48, 0xc1, 0xe2, 0x05, 0x17, 0x61, 0x5b, 0x75, 0xf5, 0x3f, 0x52, 0x2f, 0xf4,
	0xba, 0x77, 0xd2, 0x32, 0xda, 0x9d, 0x80, 0x6f, 0xca, 0xe1, 0x19, 0x34, 0x16, 0x7c, 0xa7, 0xa7,
	0x2d, 0x4c, 0xbc, 0x80, 0xd6, 0x17, 0x5b, 0x6e, 0xb9, 0x9a, 0xf7, 0x1f, 0xdd, 0x5f, 0xa6, 0xee,
	0xbd, 0x53, 0x08, 0x4d, 0xd1, 0xbf, 0x84, 0x7e, 0x45, 0x48, 0x1e, 0xc1, 0x2f, 0xdb, 0xce, 0x71,
	0x04, 0x76, 0x93, 0xa1, 0xa3, 0xe6, 0xab, 0xdd, 0x8f, 0xa5, 0xc8, 0x33, 0x04, 0xf6, 0x59, 0x73,
	0x9c, 0x40, 0x10, 0xdb, 0xab, 0xce, 0x71, 0x60, 0x07, 0x55, 0x92, 0xbc, 0x01, 0xd8, 0xd0, 0x51,
	0x9b, 0xbe, 0xfd, 0xb5, 0xe9, 0xda, 0x4e, 0x35, 0x42, 0x06, 0xd0, 0xa1, 0xfc, 0x73, 0xcb, 0xf3,
	0xa3, 0x7e, 0x11, 0x99, 0x82, 0xa7, 0xf1, 0x1c, 0x23, 0xf0, 0x84, 0xb6, 0xf5, 0x3c, 0x58, 0xa9,
	0xa4, 0x31, 0x6a, 0x98, 0xf7, 0xb6, 0xfa, 0xf7, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed,
	0x3b, 0x3c, 0x7a, 0x30, 0x03, 0x00, 0x00,
}
