// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AppMetadata;
@class Card;
@class ChargesWidget;
@class CustomersWidget;
@class Email;
@class Identifier;
@class Identity;
@class Message;
@class PlansWidget;
@class SMS;
@class SubscriptionsWidget;
@class UserMetadata;
@class UsersWidget;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ApiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ApiRoot : GPBRootObject
@end

#pragma mark - SubscribeRequest

typedef GPB_ENUM(SubscribeRequest_FieldNumber) {
  SubscribeRequest_FieldNumber_Email = 1,
  SubscribeRequest_FieldNumber_Plan = 2,
  SubscribeRequest_FieldNumber_Card = 3,
};

@interface SubscribeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *plan;

@property(nonatomic, readwrite, strong, null_resettable) Card *card;
/** Test to see if @c card has been set. */
@property(nonatomic, readwrite) BOOL hasCard;

@end

#pragma mark - UnSubscribeRequest

typedef GPB_ENUM(UnSubscribeRequest_FieldNumber) {
  UnSubscribeRequest_FieldNumber_Email = 1,
  UnSubscribeRequest_FieldNumber_Plan = 2,
};

@interface UnSubscribeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *plan;

@end

#pragma mark - Card

typedef GPB_ENUM(Card_FieldNumber) {
  Card_FieldNumber_Number = 1,
  Card_FieldNumber_ExpMonth = 2,
  Card_FieldNumber_ExpYear = 3,
  Card_FieldNumber_Cvc = 4,
};

@interface Card : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *number;

@property(nonatomic, readwrite, copy, null_resettable) NSString *expMonth;

@property(nonatomic, readwrite, copy, null_resettable) NSString *expYear;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cvc;

@end

#pragma mark - Secret

typedef GPB_ENUM(Secret_FieldNumber) {
  Secret_FieldNumber_Text = 1,
};

@interface Secret : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@end

#pragma mark - Empty

@interface Empty : GPBMessage

@end

#pragma mark - Dashboard

typedef GPB_ENUM(Dashboard_FieldNumber) {
  Dashboard_FieldNumber_Users = 1,
  Dashboard_FieldNumber_Customers = 2,
  Dashboard_FieldNumber_Plans = 3,
  Dashboard_FieldNumber_Subscriptions = 4,
  Dashboard_FieldNumber_Charges = 5,
};

@interface Dashboard : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UsersWidget *users;
/** Test to see if @c users has been set. */
@property(nonatomic, readwrite) BOOL hasUsers;

@property(nonatomic, readwrite, strong, null_resettable) CustomersWidget *customers;
/** Test to see if @c customers has been set. */
@property(nonatomic, readwrite) BOOL hasCustomers;

@property(nonatomic, readwrite, strong, null_resettable) PlansWidget *plans;
/** Test to see if @c plans has been set. */
@property(nonatomic, readwrite) BOOL hasPlans;

@property(nonatomic, readwrite, strong, null_resettable) SubscriptionsWidget *subscriptions;
/** Test to see if @c subscriptions has been set. */
@property(nonatomic, readwrite) BOOL hasSubscriptions;

@property(nonatomic, readwrite, strong, null_resettable) ChargesWidget *charges;
/** Test to see if @c charges has been set. */
@property(nonatomic, readwrite) BOOL hasCharges;

@end

#pragma mark - CustomersWidget

typedef GPB_ENUM(CustomersWidget_FieldNumber) {
  CustomersWidget_FieldNumber_Count = 1,
};

@interface CustomersWidget : GPBMessage

@property(nonatomic, readwrite) int64_t count;

@end

#pragma mark - PlansWidget

typedef GPB_ENUM(PlansWidget_FieldNumber) {
  PlansWidget_FieldNumber_Count = 1,
};

@interface PlansWidget : GPBMessage

@property(nonatomic, readwrite) int64_t count;

@end

#pragma mark - SubscriptionsWidget

typedef GPB_ENUM(SubscriptionsWidget_FieldNumber) {
  SubscriptionsWidget_FieldNumber_Count = 1,
};

@interface SubscriptionsWidget : GPBMessage

@property(nonatomic, readwrite) int64_t count;

@end

#pragma mark - ChargesWidget

typedef GPB_ENUM(ChargesWidget_FieldNumber) {
  ChargesWidget_FieldNumber_Count = 1,
  ChargesWidget_FieldNumber_Total = 2,
  ChargesWidget_FieldNumber_DollarsPerCharge = 3,
};

@interface ChargesWidget : GPBMessage

@property(nonatomic, readwrite) int64_t count;

@property(nonatomic, readwrite) double total;

@property(nonatomic, readwrite) double dollarsPerCharge;

@end

#pragma mark - UsersWidget

typedef GPB_ENUM(UsersWidget_FieldNumber) {
  UsersWidget_FieldNumber_Count = 1,
};

@interface UsersWidget : GPBMessage

@property(nonatomic, readwrite) int64_t count;

@end

#pragma mark - Identifier

typedef GPB_ENUM(Identifier_FieldNumber) {
  Identifier_FieldNumber_Id_p = 1,
};

@interface Identifier : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - SMSStatus

typedef GPB_ENUM(SMSStatus_FieldNumber) {
  SMSStatus_FieldNumber_Id_p = 1,
  SMSStatus_FieldNumber_Sms = 2,
  SMSStatus_FieldNumber_Status = 3,
  SMSStatus_FieldNumber_Uri = 4,
};

@interface SMSStatus : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Identifier *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite, strong, null_resettable) SMS *sms;
/** Test to see if @c sms has been set. */
@property(nonatomic, readwrite) BOOL hasSms;

@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

@end

#pragma mark - SMS

typedef GPB_ENUM(SMS_FieldNumber) {
  SMS_FieldNumber_Service = 1,
  SMS_FieldNumber_To = 2,
  SMS_FieldNumber_Message = 3,
  SMS_FieldNumber_MediaURL = 4,
  SMS_FieldNumber_Callback = 5,
  SMS_FieldNumber_App = 6,
};

@interface SMS : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *service;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, strong, null_resettable) Message *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mediaURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *callback;

@property(nonatomic, readwrite, copy, null_resettable) NSString *app;

@end

#pragma mark - EmailRequest

typedef GPB_ENUM(EmailRequest_FieldNumber) {
  EmailRequest_FieldNumber_FromName = 1,
  EmailRequest_FieldNumber_FromEmail = 2,
  EmailRequest_FieldNumber_Email = 3,
};

@interface EmailRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromEmail;

@property(nonatomic, readwrite, strong, null_resettable) Email *email;
/** Test to see if @c email has been set. */
@property(nonatomic, readwrite) BOOL hasEmail;

@end

#pragma mark - Email

typedef GPB_ENUM(Email_FieldNumber) {
  Email_FieldNumber_Name = 1,
  Email_FieldNumber_Address = 2,
  Email_FieldNumber_Subject = 3,
  Email_FieldNumber_Plain = 4,
  Email_FieldNumber_Html = 5,
};

@interface Email : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *subject;

@property(nonatomic, readwrite, copy, null_resettable) NSString *plain;

@property(nonatomic, readwrite, copy, null_resettable) NSString *html;

@end

#pragma mark - Call

typedef GPB_ENUM(Call_FieldNumber) {
  Call_FieldNumber_From = 1,
  Call_FieldNumber_To = 2,
  Call_FieldNumber_App = 3,
};

@interface Call : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, copy, null_resettable) NSString *app;

@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_Value = 1,
};

@interface Message : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - UserInfo

typedef GPB_ENUM(UserInfo_FieldNumber) {
  UserInfo_FieldNumber_UserId = 1,
  UserInfo_FieldNumber_Name = 2,
  UserInfo_FieldNumber_GivenName = 3,
  UserInfo_FieldNumber_FamilyName = 4,
  UserInfo_FieldNumber_Gender = 5,
  UserInfo_FieldNumber_Birthdate = 6,
  UserInfo_FieldNumber_Email = 7,
  UserInfo_FieldNumber_PhoneNumber = 8,
  UserInfo_FieldNumber_Picture = 9,
  UserInfo_FieldNumber_UserMetadata = 10,
  UserInfo_FieldNumber_AppMetadata = 11,
  UserInfo_FieldNumber_LastIp = 12,
  UserInfo_FieldNumber_Blocked = 13,
  UserInfo_FieldNumber_Nickname = 14,
  UserInfo_FieldNumber_MultifactorArray = 15,
  UserInfo_FieldNumber_CreatedAt = 17,
  UserInfo_FieldNumber_UpdatedAt = 18,
  UserInfo_FieldNumber_PhoneVerified = 19,
  UserInfo_FieldNumber_IdentitiesArray = 20,
};

@interface UserInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *givenName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *familyName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gender;

@property(nonatomic, readwrite, copy, null_resettable) NSString *birthdate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNumber;

@property(nonatomic, readwrite, copy, null_resettable) NSString *picture;

@property(nonatomic, readwrite, strong, null_resettable) UserMetadata *userMetadata;
/** Test to see if @c userMetadata has been set. */
@property(nonatomic, readwrite) BOOL hasUserMetadata;

@property(nonatomic, readwrite, strong, null_resettable) AppMetadata *appMetadata;
/** Test to see if @c appMetadata has been set. */
@property(nonatomic, readwrite) BOOL hasAppMetadata;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastIp;

@property(nonatomic, readwrite) BOOL blocked;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *multifactorArray;
/** The number of items in @c multifactorArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger multifactorArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *createdAt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *updatedAt;

@property(nonatomic, readwrite) BOOL phoneVerified;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Identity*> *identitiesArray;
/** The number of items in @c identitiesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger identitiesArray_Count;

@end

#pragma mark - Identity

typedef GPB_ENUM(Identity_FieldNumber) {
  Identity_FieldNumber_Connection = 1,
  Identity_FieldNumber_UserId = 2,
  Identity_FieldNumber_Provider = 3,
  Identity_FieldNumber_IsSocial = 4,
};

@interface Identity : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *connection;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *provider;

@property(nonatomic, readwrite, copy, null_resettable) NSString *isSocial;

@end

#pragma mark - UserMetadata

typedef GPB_ENUM(UserMetadata_FieldNumber) {
  UserMetadata_FieldNumber_Metadata = 1,
};

@interface UserMetadata : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *metadata;
/** The number of items in @c metadata without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger metadata_Count;

@end

#pragma mark - AppMetadata

typedef GPB_ENUM(AppMetadata_FieldNumber) {
  AppMetadata_FieldNumber_Metadata = 1,
};

@interface AppMetadata : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *metadata;
/** The number of items in @c metadata without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger metadata_Count;

@end

#pragma mark - Auth

typedef GPB_ENUM(Auth_FieldNumber) {
  Auth_FieldNumber_Domain = 1,
  Auth_FieldNumber_ClientId = 2,
  Auth_FieldNumber_ClientSecret = 3,
  Auth_FieldNumber_Redirect = 4,
  Auth_FieldNumber_Audience = 5,
  Auth_FieldNumber_ScopesArray = 6,
};

@interface Auth : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *domain;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientSecret;

@property(nonatomic, readwrite, copy, null_resettable) NSString *redirect;

@property(nonatomic, readwrite, copy, null_resettable) NSString *audience;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *scopesArray;
/** The number of items in @c scopesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger scopesArray_Count;

@end

#pragma mark - Bytes

typedef GPB_ENUM(Bytes_FieldNumber) {
  Bytes_FieldNumber_Bits = 1,
};

@interface Bytes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *bits;

@end

#pragma mark - Template

typedef GPB_ENUM(Template_FieldNumber) {
  Template_FieldNumber_Text = 1,
  Template_FieldNumber_Data_p = 2,
};

@interface Template : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
